version: '3.8'

services:
  data-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./models:/app/models
    ports:
      - "5000:5000"
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=5000
